DROP TABLE _Match CASCADE;
DROP TABLE Equipe CASCADE;
DROP TABLE joueur CASCADE;
DROP TABLE Gardien CASCADE;
DROP TABLE But CASCADE;
DROP TABLE est_dans_le_buts CASCADE;
DROP TABLE assiste CASCADE;
DROP TABLE joue CASCADE;