TRUNCATE TABLE Match CASCADE;
TRUNCATE TABLE Equipe CASCADE;
TRUNCATE TABLE Joueur CASCADE;
TRUNCATE TABLE Goalie CASCADE;
TRUNCATE TABLE But CASCADE;
TRUNCATE TABLE Est_Dans_Le_Buts CASCADE;
TRUNCATE TABLE assiste CASCADE;
TRUNCATE TABLE joue CASCADE;

DROP TABLE Match CASCADE;
DROP TABLE Equipe CASCADE;
DROP TABLE joueur CASCADE;
DROP TABLE goalie CASCADE;
DROP TABLE But CASCADE;
DROP TABLE est_dans_le_buts CASCADE;
DROP TABLE assiste CASCADE;
DROP TABLE joue CASCADE;



